### PR TITLE
Increase shutdown timeout to 5 minutes

### LINKED ISSUE #4192: Can't effectively set shutdownDrainDuration and shutdownFailHeathCheckDuration over 1 minute
## Expected Behavior

I would like to set frontend `shutdownDrainDuration` and `shutdownFailHeathCheckDuration` to over 1 minute and have temporal server wait the full duration for these

## Actual Behavior

Temporal server exists after 2 minutes due to the behavior of the default stop function `StopService` set in fx.go: https://github.com/temporalio/temporal/blob/master/temporal/fx.go#L292

## Steps to Reproduce the Problem

  1. set the above durations in dynamic config
  1. shutdown server
  1. observe exit after 1 minute

## Specifications

  - Version: 1.20
  - Platform: linux

### PR DESCRIPTION
**Pull request by dnr**
**What changed?**
Previously there were two 60s timeouts when shutting down (one for fx and another separately waiting for the grpc services to stop). Now there's one 5 minute timeout.

**Why?**
We might want to set drain durations longer than one or two minutes. Fixes #4192.

**How did you test it?**
Manually for now

**Potential risks**

**Is hotfix candidate?**

### CODE REVIEW

File: temporal/fx.go [hunk 1]
```diff
@@ -278,19 +274,25 @@ func (s ServerFx) Stop() error {
 	return s.app.Stop(context.Background())
 }
 
-func StopService(logger log.Logger, app *fx.App, svcName primitives.ServiceName, stopChan chan struct{}) {
-	stopCtx, cancelFunc := context.WithTimeout(context.Background(), serviceStopTimeout)
```
Comment (MichaelSnowden) [inline temporal/fx.go:282]: Let's just use the context that fx already provides to stop hooks.

**Review by MichaelSnowden — CHANGES_REQUESTED** [review]
Why can't we just remove the shutdown timeouts entirely? Timeouts exist here because someone who stops the server doesn't want wait too long for it to shutdown. We provide a non-configurable default of 60 seconds for this. If we just remove that timeout, the user can tell us exactly how long they want to wait by just sending sigint when they want to stop and sigkill when they want to force-stop. Since most of our servers are run by k8s, this is already the default behavior.

File: temporal/fx.go (hunk 1 above)
Comment (dnr) [reply temporal/fx.go:282]: Which context do you mean? This is the thing calling Stop, it's providing the context

**Review by dnr — COMMENTED** [review]
No timeout at all also works. That's a more significant change in behavior, since it means the server might hang indefinitely after a sigint/sigterm. I was aiming for a more minimal change so that this could go in a patch release (though it probably won't)

It's definitely simpler though, most of this PR goes away... do you think we should change it to no timeout?

File: temporal/fx.go (hunk 1 above)
Comment (MichaelSnowden) [reply temporal/fx.go:282]: It's not immediately available here. We should propagate it, instead of ignoring it, here: https://github.com/temporalio/temporal/blob/89f2095bf8a258835391ea48e11a3e1e03af6ba3/temporal/fx.go#L869-L871

Comment (dnr) [reply temporal/fx.go:282]: Oh, you mean passing the context from the _outer_ App to the _inner_ Apps. Yeah, we can do that. Right now it's just Background, though, that outer context doesn't use a timeout. Which makes me think... should we put the timeout on that one instead? But passing the dynamic timeout up another level will be even more messy. That makes me lean towards either no timeout or a large fixed one and forget about this dynamic thing

**Comment by dnr** [comment]
> I think we should eventually, but it requires some critical thinking about the consequences. Sorry, I don't think this should block this change.
> 
> I do think that introducing the `ExtraShutdownTimeFunc` concept, which is referenced 32 times in this change, is probably too much complexity for this patch release to allow longer timeouts.

Well, I think we decided not to include it in a patch, so let's just figure out the best long-term plan.

The number of references is what it is.. either we want the functionality (adjusting based on config), or we don't (either zero or larger fixed). I'm fine with the simpler option

File: temporal/fx.go (hunk 1 above)
Comment (dnr) [reply temporal/fx.go:282]: Wow, that was _much_ harder than I thought it would be. The problem is that the outer app wasn't actually using fx properly: it wasn't returning from Start (if configured with blocking Start, which we do in our main), and just internally stopping the inter apps from within Start, bypassing fx's Stop.

I refactored things, but it's big enough that I want to make a separate PR for it, let's leave this just for the shutdown timeout

File: common/primitives/types.go [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+// THE SOFTWARE.
+
+package primitives
+
+import "time"
+
+type (
+	// Extra time needed for shutdown (used for fx)
+	ExtraShutdownTimeFunc func() time.Duration
```
[the remark this answers is not in the document]
Comment (dnr) [reply common/primitives/types.go:31]: They're currently in dynamic config, not static. Yes, static arguably makes more sense here, but I don't want to change the way they're configured

File: temporal/fx.go [hunk 3]
```diff
@@ -278,19 +274,25 @@ func (s ServerFx) Stop() error {
...
 		logger.Error("Failed to stop service", tag.Service(svcName), tag.Error(err))
 	}
 
 	// verify "Start" goroutine returned
 	select {
 	case <-stopChan:
-	case <-time.After(time.Minute):
-		logger.Error("Timed out (1 minute) waiting for service to stop.", tag.Service(svcName))
+	case <-stopCtx.Done():
+		logger.Error("Timed out waiting for service to stop", tag.Service(svcName))
```
[the remark this answers is not in the document]
Comment (dnr) [reply temporal/fx.go:295]: We don't know here how it can be changed, each service can decide that independently. We can list a few relevant dynamic configs in the error message but that might get out of sync with the code

**Review by dnr — COMMENTED** [review]
Let's just have a discussion on whether this should even be dynamic. If we decide not, most of this is moot

**Review by MichaelSnowden — APPROVED** [review]
