### PR TITLE
Set timeout for all Elasticsearch read calls

### LINKED ISSUE #581: Calls to Elasticsearch does not specify any timeout
All visibility API calls to elastic search does not set any timeout:
https://github.com/temporalio/temporal/blob/master/common/persistence/elasticsearch/esVisibilityStore.go#L395
```
ctx := context.Background()
	searchResult, err := v.esClient.SearchWithDSL(ctx, v.index, queryDSL)
	if err != nil {
		return nil, serviceerror.NewInternal(fmt.Sprintf("ListWorkflowExecutions failed. Error: %v", err))
	}
```

### PR DESCRIPTION
**Pull request by alexshtin**
**What changed?**
Set timeout (16 seconds) for all Elasticsearch read calls.

**Why?**
Closes #581.

**How did you test it?**
Existing tests.

**Potential risks**
Calls to Elasticsearch longer than 16 seconds will start to fail. But our RPC timeout is shorter so no real calls should be affected.

**Is hotfix candidate?**
No.

### CODE REVIEW

File: common/persistence/visibility/store/elasticsearch/visibility_store.go [hunk 1]
```diff
@@ -107,6 +109,11 @@ func NewVisibilityStore(
 	}
 }
 
+func newReadContext() context.Context {
+	ctx, _ := context.WithTimeout(context.Background(), readTimeout)
+	return ctx
+}
+
```
Comment (wxing1292) [inline common/persistence/visibility/store/elasticsearch/visibility_store.go:116]: probably need to used the cancel function? e.g. timeout is pretty much like a timer

**Review by wxing1292 — APPROVED** [review]
