### PR TITLE
Set task queue kind explicitly

### LINKED ISSUE #543: TaskQueue Kind not set for Scheduled WorkflowTask
## Expected Behavior
Should be able to see Kind set to either `Normal` or `Sticky`

## Actual Behavior
Here is the output I see from tctl:
```
11  2020-07-14T19:34:11-07:00  WorkflowTaskScheduled           {TaskQueue:{Name:Samars-MacBook-Pro.local:fc872005-0526-4fc6-892b-8614d6ad7cc6,
                                                                 Kind:Unspecified}, StartToCloseTimeoutSeconds:10, Attempt:0}
```

## Steps to Reproduce the Problem

  1. Start workflow execution
  1. `./tctl wf show -w <id>`

## Specifications

  - Version:
  - Platform:

### PR DESCRIPTION
**Pull request by alexshtin**
**What changed?**
`TaskQueue.Kind` is set to `Normal` explicitly.

**Why?**
Closes #543.

**How did you test it?**
Run helloworlds workflow and check the history:
```
   1  WorkflowExecutionStarted    {WorkflowType:{Name:Workflow}, ParentInitiatedEventId:0,             
                                  TaskQueue:{Name:hello-world, Kind:Normal},                           
                                  Input:[Temporal], WorkflowExecutionTimeoutSeconds:315360000,         
                                  WorkflowRunTimeoutSeconds:315360000,                                 
                                  WorkflowTaskTimeoutSeconds:10,                                       
                                  Initiator:Workflow, LastCompletionResult:[],                         
                                  OriginalExecutionRunId:08b6f8ab-4a66-479c-88dd-8d06c0501d06,         
                                  Identity:30911@ShtinUbuntu2@,                                        
                                  FirstExecutionRunId:08b6f8ab-4a66-479c-88dd-8d06c0501d06,            
                                  Attempt:0, WorkflowExecutionExpirationTimestamp:0,                   
                                  FirstWorkflowTaskBackoffSeconds:0, Header:{Fields:map{}}}            
   2  WorkflowTaskScheduled       {TaskQueue:{Name:hello-world,                                        
                                  Kind:Normal},                                                        
                                  StartToCloseTimeoutSeconds:10,                                       
                                  Attempt:0}                                                           
   3  WorkflowTaskStarted         {ScheduledEventId:2,                                                 
                                  Identity:30854@ShtinUbuntu2@,                                        
                                  RequestId:879af38e-9cfb-43d1-a792-07b9e7b36e38}                      
   4  WorkflowTaskCompleted       {ScheduledEventId:2, StartedEventId:3,                               
                                  Identity:30854@ShtinUbuntu2@,                                        
                                  BinaryChecksum:5bb8b2a439e0620147f36bd0b6d3b132}                     
   5  ActivityTaskScheduled       {ActivityId:5,                                                       
                                  ActivityType:{Name:Activity},                                        
                                  TaskQueue:{Name:hello-world,                                         
                                  Kind:Normal}, Header:{Fields:map{}},                                 
                                  Input:[Temporal],                                                    
                                  ScheduleToCloseTimeoutSeconds:315360000,                             
                                  ScheduleToStartTimeoutSeconds:60,                                    
                                  StartToCloseTimeoutSeconds:60,                                       
                                  HeartbeatTimeoutSeconds:0,                                           
                                  WorkflowTaskCompletedEventId:4}                                      
   6  ActivityTaskStarted         {ScheduledEventId:5,                                                 
                                  Identity:30854@ShtinUbuntu2@,                                        
                                  RequestId:7470a7cf-7e7a-4374-87ad-a78859d9b233,                      
                                  Attempt:0}                                                           
   7  ActivityTaskCompleted       {Result:[Hello Temporal!],                                           
                                  ScheduledEventId:5,                                                  
                                  StartedEventId:6,                                                    
                                  Identity:30854@ShtinUbuntu2@}                                        
   8  WorkflowTaskScheduled       {TaskQueue:{Name:ShtinUbuntu2:84fa167b-bc49-4120-84a0-3f8571f46686,  
                                  Kind:Sticky}, StartToCloseTimeoutSeconds:10, Attempt:0}              
   9  WorkflowTaskStarted         {ScheduledEventId:8,                                                 
                                  Identity:30854@ShtinUbuntu2@,                                        
                                  RequestId:1d1196e5-4b44-4df8-976b-efe415101bc7}                      
  10  WorkflowTaskCompleted       {ScheduledEventId:8, StartedEventId:9,                               
                                  Identity:30854@ShtinUbuntu2@,                                        
                                  BinaryChecksum:5bb8b2a439e0620147f36bd0b6d3b132}                     
  11  WorkflowExecutionCompleted  {Result:[Hello Temporal!],                                           
                                  WorkflowTaskCompletedEventId:10}  
```

**Potential risks**
No risks.

### CODE REVIEW

File: tools/cli/adminTaskQueueCommands.go [hunk 1]
```diff
@@ -54,8 +54,11 @@ func AdminDescribeTaskQueue(c *cli.Context) {
 	ctx, cancel := newContext(c)
 	defer cancel()
 	request := &workflowservice.DescribeTaskQueueRequest{
-		Namespace:              namespace,
-		TaskQueue:              &taskqueuepb.TaskQueue{Name: taskQueue},
+		Namespace: namespace,
+		TaskQueue: &taskqueuepb.TaskQueue{
+			Name: taskQueue,
+			Kind: enumspb.TASK_QUEUE_KIND_NORMAL,
```
Comment (alexshtin) [inline tools/cli/adminTaskQueueCommands.go:60]: Should `kind` be a command line parameter also?

File: service/history/historyBuilder.go [hunk 2]
```diff
@@ -87,14 +87,14 @@ func (b *historyBuilder) AddWorkflowExecutionStartedEvent(request *historyservic
 	return b.addEventToHistory(event)
 }
 
-func (b *historyBuilder) AddWorkflowTaskScheduledEvent(taskQueue string,
+func (b *historyBuilder) AddWorkflowTaskScheduledEvent(taskQueue *taskqueuepb.TaskQueue,
```
Comment (alexshtin) [inline service/history/historyBuilder.go:90]: All these funcs now accepts `TaskQueue` object, not task queue name.

File: service/frontend/workflowHandler.go [hunk 3]
```diff
@@ -3087,10 +3090,6 @@ func (wh *WorkflowHandler) DescribeTaskQueue(ctx context.Context, request *workf
 		return nil, err
 	}
 
-	if request.GetTaskQueueType() == enumspb.TASK_QUEUE_TYPE_UNSPECIFIED {
-		return nil, wh.error(errTaskQueueTypeNotSet, scope)
-	}
-
```
Comment (alexshtin) [inline service/frontend/workflowHandler.go:3093]: It can't happen because validator above will set it to default value,

File: tools/cli/adminTaskQueueCommands.go (hunk 1 above)
Comment (samarabbas) [reply tools/cli/adminTaskQueueCommands.go:60]: Probably not right now.  Sticky task queue names are auto generated and cannot have duplicates.
