### PR TITLE
Return Unavailable to frontend rpcs until healthy

### LINKED ISSUE #5015: gRPC health check may say the server is unhealthy even if it's responding successfully to GetSystemInfo
For full context, see the discussion on this PR: https://github.com/temporalio/cli/pull/368#discussion_r1366898403

## Expected Behavior

If GetSystemInfo returns successfully, the gRPC health check should also pass.

## Actual Behavior

For a period of up to about 1 second after GetSystemInfo succeeds, the gRPC health check may fail (returning NOT_SERVING), falsely indicating that gRPC is down when it's not.

This was causing frequent intermittent failures (such as [this one](https://github.com/temporalio/cli/actions/runs/6317569213/job/17154638693#step:5:199)) in the CLI CI/CD pipeline until we worked around it in https://github.com/temporalio/cli/pull/368 .

## Steps to Reproduce the Problem

  1. Launch the server
  2. Immediately try to connect to it using the Go SDK. (The Go SDK will wait for a successful GetSystemInfo response before returning a client object to the caller.)
  3. Once the Go SDK returns a client object, immediately use the client object to perform a health check of the server.
  4. Intermittently, the health check will fail. 

## Specifications

  - Version: 1.22.0
  - Platform: Seen on all platforms

### PR DESCRIPTION
**Pull request by dnr**
**What changed?**
Add an interceptor to return Unavailable to WorkflowService methods until the frontend considers itself "healthy", which currently means "membership is initialized".

**Why?**
Fixes #5015 

**How did you test it?**
mostly manually

**Potential risks**
This adds a window of time where frontend can now return Unavailable where previously it might have succeeded or returned a different error code. Specifically note that client.Dial in go sdk (at least) will fail fast on this error and the caller will need to retry.

### CODE REVIEW

File: common/rpc/interceptor/health.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+
+func (i *HealthInterceptor) Intercept(
+	ctx context.Context,
+	req interface{},
+	info *grpc.UnaryServerInfo,
+	handler grpc.UnaryHandler,
+) (interface{}, error) {
+	// only enforce health check on WorkflowService
+	servicePrefix, _ := SplitMethodName(info.FullMethod)
+	if servicePrefix == api.WorkflowServicePrefix {
```
Comment (tdeebswihart) [inline common/rpc/interceptor/health.go:60]: Why bother splitting the path? You can just check for a prefix:
```suggestion
    if strings.HasPrefix(info.FullMethod, api.WorkflowServicePrefix) {
```

Comment (dnr) [reply common/rpc/interceptor/health.go:60]: fair point. all the other interceptors use that function so it seemed fitting

Comment (dnr) [reply common/rpc/interceptor/health.go:60]: also, comments welcome on whether it should apply to other services too. on second thought it should probably be workflowservice + operatorservice

Comment (tdeebswihart) [reply common/rpc/interceptor/health.go]: Are there services it _shouldnt'_ apply to?

Comment (dnr) [reply common/rpc/interceptor/health.go]: I would argue not AdminService, since theoretically there might be something in there to repair an unhealthy frontend (although there's nothing like that now).
And also not grpc health service, since that should be able to return successful "not serving" responses.

**Review by tdeebswihart — APPROVED** [review]
