### PR TITLE
Fix TestCronWorkflow and TestCronChildWorkflowExecution integration tests

### LINKED ISSUE #591: TestIntegrationSuite/TestCronWorkflow is flaky
```
    integration_test.go:1034: 
        	Error Trace:	integration_test.go:1034
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 2
        	Test:       	TestIntegrationSuite/TestCronWorkflow
        	Messages:   	exected backoff 2-0 should be multiplier of target backoff 3
```

Line number might need some alignment.

### PR DESCRIPTION
**Pull request by dnr**
**What changed?**

These tests were skipped because they were flaky (and had some other bugs). Cleaned up the logic and made them more reliable.

**Why?**

More testing. Fixes #591 and #592.

**How did you test it?**

Ran 100 times each on my local machine

**Potential risks**

**Is hotfix candidate?**

### CODE REVIEW

File: host/child_workflow_test.go [hunk 1]
```diff
@@ -275,24 +267,31 @@ func (s *integrationSuite) TestCronChildWorkflowExecution() {
 		Identity:            identity,
 	}
 
+	// Because of rounding in GetBackoffForNextSchedule, we'll tend to stay aligned to whatever
```
Comment (yiminc) [inline host/child_workflow_test.go:270]: Can we fix the rounding issue instead? The rounding was needed because the backoff used to be seconds. Now I it is time.Duration so i believe rounding is no longer needed.

**Review by yiminc — APPROVED** [review]

File: host/child_workflow_test.go (hunk 1 above)
Comment (dnr) [reply host/child_workflow_test.go:270]: I was going to try that later, but thought I should get the tests working without any behavior changes first. I can try to just remove the rounding if you think it's low risk. One small potential risk is that preserving the phase within the second is a very crude sort of jitter, that might be beneficial to users with huge numbers of cron workflows that start at the same time.
