### PR TITLE
Use Failure and FailureInfo for errors

### LINKED ISSUE #89: Refactor Failure representation in the APIs
Currently failures in all customer facing proto structures (not gRPC ones) are represented by two fields `reason` and `details`. This kind of works when all parts of a workflow are implemented in a single language. For example Java SDK serializes complete exception chain including stack trace of each exception into the details field. The problem is this serialization/deserialization code is completely Java specific. Now as Python client is added it uses different format for the stack trace. Go (in case of panic) also might require stack trace serialization/deserialization. Even without stack traces chaining of errors coming from SDKs in different languages is practically impossible without unifying the serialization format.

The proposal is that instead of unifying the serialization format, model the chain of errors with attached strack traces through a generic protobuf structure. This way no language specific serialization is necessary and errors coming from different components can be chained even if they are from different languages.

The strawman API changes.
```
message ApplicationFailureInfo {
    string sdk = 1; // java, go, python, etc
    string message = 2;
    string type = 3; // Exception class,  Go error type, etc.
    bytes details = 4; // Possibly error payload beyond the message.
}

message ActivityTaskFailureInfo {
    int64 scheduledEventId = 1;
    int64 startedEventId = 2;
    string identity = 3;
}

message ChildWorkflowExecutionFailureInfo {
    string domain = 1;
    WorkflowExecution workflowExecution = 2;
    WorkflowType workflowType = 3;
    int64 initiatedEventId = 4;
    int64 startedEventId = 5;
}

message Failure {
    oneof failureInfo {
        ActivityTaskFailureInfo activityTaskFailureInfo = 1;
        ChildWorkflowExecutionFailureInfo childWorkflowExecutionFailureInfo = 2;
        ApplicationFailureInfo applicationFailureInfo = 3;
    }
    repeated string backtrace = 4;
}

message FailureChain {
    repeated Failure failures = 1; // The initial cause is the first in the list
}
```
An open question if providing a typed backtrace would bring any value. For example it can be modeled as 
```
message StackTraceElement {
    string file = 1;
    int32 line = 2;
    string component = 3; // declaringClass for Java, module for Go
    string function = 4;
}
```
But it might require more fields for some languages for example PHP stack trace is much reacher:
https://www.php.net/manual/en/function.debug-backtrace.php

### PR DESCRIPTION
**Pull request by alexshtin**
**What changed?**
`Failure` and `FailureInfo` structures are used to store error information. Closes #89.

**Why?**
Described in #89.

**How did you test it?**
Run all tests.

**Potential risks**
Errors are not handled properly.

### CODE REVIEW

File: common/persistence/dataInterfaces.go [hunk 1]
```diff
@@ -545,9 +546,8 @@ type (
 		ExpirationTime     time.Time
 		MaximumAttempts    int32
 		NonRetriableErrors []string
```
Comment (samarabbas) [inline common/persistence/dataInterfaces.go:548]: Maybe you want to rename this field too?

File: common/util.go [hunk 2]
```diff
@@ -79,17 +79,13 @@ const (
...
+	FailureReasonFailureExceedsLimit = "Failure exceeds size limit."
 	// FailureReasonCancelDetailsExceedsLimit is failureReason for cancel details exceeds limit
-	FailureReasonCancelDetailsExceedsLimit = "CANCEL_DETAILS_EXCEEDS_LIMIT"
+	FailureReasonCancelDetailsExceedsLimit = "Cancel details exceed size limit."
 	// FailureReasonHeartbeatExceedsLimit is failureReason for heartbeat exceeds limit
-	FailureReasonHeartbeatExceedsLimit = "HEARTBEAT_EXCEEDS_LIMIT"
-	// FailureReasonDecisionBlobSizeExceedsLimit is the failureReason for decision blob exceeds size limit
-	FailureReasonDecisionBlobSizeExceedsLimit = "DECISION_BLOB_SIZE_EXCEEDS_LIMIT"
-	// FailureReasonSizeExceedsLimit is reason to fail workflow when history size or count exceed limit
-	FailureReasonSizeExceedsLimit = "HISTORY_EXCEEDS_LIMIT"
```
Comment (samarabbas) [inline common/util.go:92]: Why is this gone? This is a legitimate failure case.

File: service/frontend/workflowHandler.go [hunk 3]
```diff
@@ -1002,8 +1003,12 @@ func (wh *WorkflowHandler) RespondDecisionTaskFailed(ctx context.Context, reques
 		wh.GetThrottledLogger(),
 		tag.BlobSizeViolationOperation("RespondDecisionTaskFailed"),
 	); err != nil {
+		serverFailure := failure.NewServerFailure(common.FailureReasonFailureExceedsLimit, false)
+		serverFailure.Cause = failure.Truncate(request.Failure, sizeLimitWarn)
+		request.Failure = serverFailure
+
 		// details exceed, we would just truncate the size for decision task failed as the details is not used anywhere by client code
-		request.Details = nil
+		request.Failure = nil
```
Comment (samarabbas) [inline service/frontend/workflowHandler.go:1011]: I'm confused by this piece of logic.  First we set `request.Failure` to `serverFailure` and then we immediately set it to nil.

File: service/frontend/workflowHandler.go [hunk 4]
```diff
@@ -1188,8 +1193,7 @@ func (wh *WorkflowHandler) RecordActivityTaskHeartbeat(ctx context.Context, requ
 		// heartbeat details exceed size limit, we would fail the activity immediately with explicit error reason
 		failRequest := &workflowservice.RespondActivityTaskFailedRequest{
 			TaskToken: request.TaskToken,
-			Reason:    common.FailureReasonHeartbeatExceedsLimit,
-			Details:   nil,
+			Failure:   failure.NewServerFailure(common.FailureReasonHeartbeatExceedsLimit, true),
```
Comment (samarabbas) [inline service/frontend/workflowHandler.go:1196]: Setting isRetryable to `true` for size exceeded could be really dangerous.

File: service/frontend/workflowHandler.go [hunk 5]
```diff
@@ -1295,8 +1299,7 @@ func (wh *WorkflowHandler) RecordActivityTaskHeartbeatById(ctx context.Context,
 		// heartbeat details exceed size limit, we would fail the activity immediately with explicit error reason
 		failRequest := &workflowservice.RespondActivityTaskFailedRequest{
 			TaskToken: token,
-			Reason:    common.FailureReasonHeartbeatExceedsLimit,
-			Details:   nil,
+			Failure:   failure.NewServerFailure(common.FailureReasonHeartbeatExceedsLimit, true),
```
Comment (samarabbas) [inline service/frontend/workflowHandler.go:1302]: Setting isRetryable to true for size exceeded could be really dangerous.

File: service/frontend/workflowHandler.go [hunk 6]
```diff
@@ -1392,8 +1395,7 @@ func (wh *WorkflowHandler) RespondActivityTaskCompleted(ctx context.Context, req
 		// result exceeds blob size limit, we would record it as failure
 		failRequest := &workflowservice.RespondActivityTaskFailedRequest{
 			TaskToken: request.TaskToken,
-			Reason:    common.FailureReasonCompleteResultExceedsLimit,
-			Details:   nil,
+			Failure:   failure.NewServerFailure(common.FailureReasonCompleteResultExceedsLimit, true),
```
Comment (samarabbas) [inline service/frontend/workflowHandler.go:1398]: Setting isRetryable to true for size exceeded could be really dangerous.

File: service/frontend/workflowHandler.go [hunk 7]
```diff
@@ -1501,8 +1503,7 @@ func (wh *WorkflowHandler) RespondActivityTaskCompletedById(ctx context.Context,
 		// result exceeds blob size limit, we would record it as failure
 		failRequest := &workflowservice.RespondActivityTaskFailedRequest{
 			TaskToken: token,
-			Reason:    common.FailureReasonCompleteResultExceedsLimit,
-			Details:   nil,
+			Failure:   failure.NewServerFailure(common.FailureReasonCompleteResultExceedsLimit, true),
```
Comment (samarabbas) [inline service/frontend/workflowHandler.go:1506]: Setting isRetryable to true for size exceeded could be really dangerous.

File: service/frontend/workflowHandler.go [hunk 8]
```diff
@@ -1784,8 +1784,7 @@ func (wh *WorkflowHandler) RespondActivityTaskCanceled(ctx context.Context, requ
 		// details exceeds blob size limit, we would record it as failure
 		failRequest := &workflowservice.RespondActivityTaskFailedRequest{
 			TaskToken: request.TaskToken,
-			Reason:    common.FailureReasonCancelDetailsExceedsLimit,
-			Details:   nil,
+			Failure:   failure.NewServerFailure(common.FailureReasonCancelDetailsExceedsLimit, true),
```
Comment (samarabbas) [inline service/frontend/workflowHandler.go:1787]: Setting isRetryable to true for size exceeded could be really dangerous.

File: service/frontend/workflowHandler.go [hunk 9]
```diff
@@ -1892,8 +1891,7 @@ func (wh *WorkflowHandler) RespondActivityTaskCanceledById(ctx context.Context,
 		// details exceeds blob size limit, we would record it as failure
 		failRequest := &workflowservice.RespondActivityTaskFailedRequest{
 			TaskToken: token,
-			Reason:    common.FailureReasonCancelDetailsExceedsLimit,
-			Details:   nil,
+			Failure:   failure.NewServerFailure(common.FailureReasonCancelDetailsExceedsLimit, true),
```
Comment (samarabbas) [inline service/frontend/workflowHandler.go:1894]: Setting isRetryable to true for size exceeded could be really dangerous.

File: service/history/decisionChecker.go [hunk 10]
```diff
@@ -170,8 +169,7 @@ func (c *workflowSizeChecker) failWorkflowSizeExceedsLimit() (bool, error) {
 			tag.WorkflowEventCount(historyCount))
 
 		attributes := &decisionpb.FailWorkflowExecutionDecisionAttributes{
-			Reason:  common.FailureReasonSizeExceedsLimit,
-			Details: payloads.EncodeString("Workflow history size / count exceeds limit."),
+			Failure: failure.NewServerFailure("Workflow history size / count exceeds limit.", false),
```
Comment (samarabbas) [inline service/history/decisionChecker.go:172]: Looks like you are breaking the pattern here from other server failures.  Is there a specific reason to treat these slightly differently.

Comment (alexshtin) [reply service/history/decisionChecker.go:172]: No, just overlooked. Moved message to constant.

File: common/util.go (hunk 2 above)
Comment (alexshtin) [reply common/util.go:92]: Restored `FailureReasonSizeExceedsLimit`. And `FailureReasonDecisionBlobSizeExceedsLimit` is not needed anymore because there are 8 different messages used for this type of failure. And constant was used to determinate retryable, which is seprate field now.

File: service/frontend/workflowHandler.go (hunk 3 above)
Comment (alexshtin) [reply service/frontend/workflowHandler.go:1011]: I literally forgot to remove these 3 lines after I wrote 3 lines above. Great catch!

File: service/frontend/workflowHandler.go (hunk 4 above)
Comment (alexshtin) [reply service/frontend/workflowHandler.go:1196]: The field is actually called `nonRetryable`, and `true` means "don't retry". Logic is stayed the same here.
