### PR TITLE
RespondWorkflowTaskCompleted returns error on bad commands

### LINKED ISSUE #652: respondWorkflowTaskCompleted doesn't fail on bad commands
## Expected Behavior
`respondWorkflowTaskCompleted` call is expected to throw `INVALID_ARGUMENT` gRPC failure if commands are not formatted properly.

## Actual Behavior
`respondWorkflowTaskCompleted` returns OK empty response.

The service logs in my case:

`temporal_1              | {"level":"info","ts":"2020-08-03T00:13:37.102Z","msg":"Failing the workflow task.","service":"history","shard-id":1,"address":"172.21.0.3:7234","shard-item":"0xc00048c700","component":"history-engine","workflow-task-fail-cause":"BadRecordMarkerAttributes","error":"RecordMarkerCommandAttributes is not set on command.","wf-id":"c511cd7d-d53b-4e7a-ac71-3e40c645d913","wf-run-id":"d1072956-9718-48b3-9882-cb892965450b","wf-namespace-id":"5d0413eb-9cfc-48f5-b6ff-6df341eed0ce","logging-call-at":"workflowTaskHandlerCallbacks.go:456"}`

## Steps to Reproduce the Problem

The following Java class reproduces the problem:

```java
public class BadDecisionRepro {

  public static final String TASK_QUEUE = "queue1";

  public static void main(String[] args) {
    WorkflowServiceStubs service = WorkflowServiceStubs.newInstance();
    WorkflowServiceGrpc.WorkflowServiceBlockingStub stub = service.blockingStub();

    stub.startWorkflowExecution(
        StartWorkflowExecutionRequest.newBuilder()
            .setNamespace("default")
            .setRequestId(UUID.randomUUID().toString())
            .setWorkflowId(UUID.randomUUID().toString())
            .setWorkflowType(WorkflowType.newBuilder().setName("type1").build())
            .setTaskQueue(TaskQueue.newBuilder().setName("queue1").build())
            .build());

    PollWorkflowTaskQueueRequest pollRequest =
        PollWorkflowTaskQueueRequest.newBuilder()
            .setNamespace("default")
            .setTaskQueue(TaskQueue.newBuilder().setName(TASK_QUEUE))
            .build();
    PollWorkflowTaskQueueResponse task = stub.pollWorkflowTaskQueue(pollRequest);

    RespondWorkflowTaskCompletedRequest.Builder respondRequest =
        RespondWorkflowTaskCompletedRequest.newBuilder()
            .setTaskToken(task.getTaskToken())
            .addCommands(
                0,
                Command.newBuilder()
                    .setCommandType(CommandType.COMMAND_TYPE_RECORD_MARKER)
                    .build());

    RespondWorkflowTaskCompletedResponse response =
        stub.respondWorkflowTaskCompleted(respondRequest.build());
    
    System.out.println("Response='" + response + "'");
  }
}

```

## Specifications

  - Version: 0.28.0 of the service
  - Platform: Mac

### PR DESCRIPTION
**Pull request by alexshtin**
**What changed?**
If `failWorkflowTask` was created in `completeWorkflowTask` then entire request fails.

**Why?**
Fixes #652.

**How did you test it?**
Added integration test.

**Potential risks**
If anyone relies on success return in case of malformed request (very unlikely), their code will be broken.

### CODE REVIEW

File: service/history/workflowTaskHandlerCallbacks.go [hunk 1]
```diff
@@ -564,7 +557,16 @@ Update_History_Loop:
...
+			return nil, serviceerror.NewNotFound("workflow task heartbeat timeout")
+		}
+
+		if workflowTaskFailedErr != nil {
+			switch workflowTaskFailedErr.causeErr.(type) {
+			case nil:
+				return nil, serviceerror.NewInternal(workflowTaskFailedErr.Error())
+			case *serviceerror.InvalidArgument:
+				return nil, serviceerror.NewInvalidArgument(workflowTaskFailedErr.Error())
+			}
```
Comment (alexshtin) [inline service/history/workflowTaskHandlerCallbacks.go:569]: This is an actual change of this PR. I am not sure about `nil` case though. It only happens when `handler.hasBufferedEvents` is `true` and reason is `WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND`. Should it be `InvalidArgument` or `Internal` fits better here?

File: service/history/workflowTaskHandlerCallbacks.go [hunk 2]
```diff
@@ -564,7 +557,16 @@ Update_History_Loop:
 
 		if workflowTaskHeartbeatTimeout {
 			// at this point, update is successful, but we still return an error to client so that the worker will give up this workflow
-			return nil, serviceerror.NewNotFound(fmt.Sprintf("workflow task heartbeat timeout"))
+			return nil, serviceerror.NewNotFound("workflow task heartbeat timeout")
+		}
+
+		if workflowTaskFailedErr != nil {
+			switch workflowTaskFailedErr.causeErr.(type) {
```
Comment (samarabbas) [inline service/history/workflowTaskHandlerCallbacks.go:564]: I don't like that we have logic about what error to return back to the caller spread across multiple files.  I think we should have the workflow task error logic only within workflowTaskHandler.go.

File: service/history/workflowTaskHandlerCallbacks.go (hunk 1 above)
Comment (samarabbas) [reply service/history/workflowTaskHandlerCallbacks.go:569]: I don't think we should be setting the workflowTaskError to nil when we return an error back to user because workflow task has Completed command and there are some unhandled events in the buffer.  I think we should be returning back InvalidArgument error back to the caller because we don't want user to retry this workflow task completion.

File: service/history/historyEngine.go [hunk 3]
```diff
@@ -2563,7 +2562,7 @@ func (e *historyEngineImpl) failWorkflowTask(
 	}
 
 	if _, err = mutableState.AddWorkflowTaskFailedEvent(
-		scheduleID, startedID, cause, failure, request.GetIdentity(), request.GetBinaryChecksum(), "", "", 0,
+		scheduleID, startedID, workflowTaskFailedErr.failedCause, failure.NewServerFailure(workflowTaskFailedErr.Error(), true), request.GetIdentity(), request.GetBinaryChecksum(), "", "", 0,
```
Comment (samarabbas) [inline service/history/historyEngine.go:2565]: Why are we wrapping it in `NewServerFailure`?

Comment (samarabbas) [reply service/history/historyEngine.go:2565]: Maybe we can add another method on workflowTaskFailedErr type to convert it into right format to add an history event for it.

Comment (alexshtin) [reply service/history/historyEngine.go]: `WorkflowTaskFailedEvent` has failure field which may contains different failures. Here it is just error message but other places may set other failures. The best way to refactor this, is to replace `workflowTaskFailedError` with `WorkflowTaskFailure` which will contains `failedCause` enum and error message. I don't know if it worth it. I would leave it as is for now.
