### PR TITLE
Use search attribute type map in visibility archival

### LINKED ISSUE #4270: archival + task error after migration from 1.19.1 to 1.20.0
## Expected Behavior
no error

## Actual Behavior

after a migration process from 1.19.1 to 1.20.0, we got a lot of error : 
"failed to archive target" -> "invalid search attribute type : Unspecified"
"failed to archive workflow" -> "invalid search attribute type : Unspecified"
"failed to process task" -> "invalid search attribute type : Unspecified"

failed to archive target return this stack : 
```
[go.temporal.io/server/common/log.(*zapLogger).Error](http://go.temporal.io/server/common/log.(*zapLogger).Error)
    /home/builder/temporal/common/log/zap_logger.go:150
[go.temporal.io/server/service/history/archival.(*archiver).recordArchiveTargetResult](http://go.temporal.io/server/service/history/archival.(*archiver).recordArchiveTargetResult)
    /home/builder/temporal/service/history/archival/archiver.go:244
[go.temporal.io/server/service/history/archival.(*archiver).archiveVisibility](http://go.temporal.io/server/service/history/archival.(*archiver).archiveVisibility)
    /home/builder/temporal/service/history/archival/archiver.go:218
[go.temporal.io/server/service/history/archival.(*archiver).Archive.func3](http://go.temporal.io/server/service/history/archival.(*archiver).Archive.func3)
    /home/builder/temporal/service/history/archival/archiver.go:167
```

failed to process task return this stack :
```
go.temporal.io/server/common/log.(*zapLogger).Error](http://go.temporal.io/server/common/log.(*zapLogger).Error)
    /home/builder/temporal/common/log/zap_logger.go:150
[go.temporal.io/server/common/log.(*lazyLogger).Error](http://go.temporal.io/server/common/log.(*lazyLogger).Error)
    /home/builder/temporal/common/log/lazy_logger.go:68
[go.temporal.io/server/service/history/queues.(*executableImpl).HandleErr](http://go.temporal.io/server/service/history/queues.(*executableImpl).HandleErr)
    /home/builder/temporal/service/history/queues/executable.go:321
[go.temporal.io/server/common/tasks.(*FIFOScheduler[...]).executeTask.func1](http://go.temporal.io/server/common/tasks.(*FIFOScheduler%5B...%5D).executeTask.func1)
    /home/builder/temporal/common/tasks/fifo_scheduler.go:232
[go.temporal.io/server/common/backoff.ThrottleRetry.func1](http://go.temporal.io/server/common/backoff.ThrottleRetry.func1)
    /home/builder/temporal/common/backoff/retry.go:175
[go.temporal.io/server/common/backoff.ThrottleRetryContext](http://go.temporal.io/server/common/backoff.ThrottleRetryContext)
    /home/builder/temporal/common/backoff/retry.go:199
[go.temporal.io/server/common/backoff.ThrottleRetry](http://go.temporal.io/server/common/backoff.ThrottleRetry)
    /home/builder/temporal/common/backoff/retry.go:176
[go.temporal.io/server/common/tasks.(*FIFOScheduler[...]).executeTask](http://go.temporal.io/server/common/tasks.(*FIFOScheduler%5B...%5D).executeTask)
    /home/builder/temporal/common/tasks/fifo_scheduler.go:241
[go.temporal.io/server/common/tasks.(*FIFOScheduler[...]).processTask](http://go.temporal.io/server/common/tasks.(*FIFOScheduler%5B...%5D).processTask)
    /home/builder/temporal/common/tasks/fifo_scheduler.go:217"
```
i'll try to migrate to 1.20.2 but same problem.

workers seems to run normally but i get errors on temporal logs.

## Steps to Reproduce the Problem

migrate from v1.19.1 to 1.20.0

## Specifications

  - Version: 1.20.2
  - Platform: kubernetes
  - archivage : S3
  - database : PG (migrated to V12 but problem before)
  - process using schedules

```
temporal-tools-84c7c5cb75-5m55t:~$ tctl adm cl gsa
Custom search attributes:
+------+------+
| NAME | TYPE |
+------+------+
+------+------+
System search attributes:
+----------------------------+-------------+
|            NAME            |    TYPE     |
+----------------------------+-------------+
| BatcherNamespace           | Keyword     |
| BatcherUser                | Keyword     |
| BinaryChecksums            | KeywordList |
| CloseTime                  | Datetime    |
| ExecutionDuration          | Int         |
| ExecutionStatus            | Keyword     |
| ExecutionTime              | Datetime    |
| HistoryLength              | Int         |
| HistorySizeBytes           | Int         |
| RunId                      | Keyword     |
| StartTime                  | Datetime    |
| StateTransitionCount       | Int         |
| TaskQueue                  | Keyword     |
| TemporalChangeVersion      | KeywordList |
| TemporalNamespaceDivision  | Keyword     |
| TemporalSchedulePaused     | Bool        |
| TemporalScheduledById      | Keyword     |
| TemporalScheduledStartTime | Datetime    |
| WorkflowId                 | Keyword     |
| WorkflowType               | Keyword     |
+----------------------------+-------------+
Storage mappings:
+-------------+-------------+
| COLUMN NAME | COLUMN TYPE |
+-------------+-------------+
+-------------+-------------+
Workflow info:
{

}
```

### PR DESCRIPTION
**Pull request by MichaelSnowden**
**What changed?**
We now populate search attributes with type information before archiving them.

**Why?**
This information is not always embedded in the fields themselves, e.g., for schedules. This fixes #4270 .

**How did you test it?**
I reproduced the linked issue without this change, and then verified that it worked after this change. I repro'd by doing this:
1. Check out 1.20.2
2. Start a server pointing at pg12 and s3
3. Archive a scheduled workflow
4. Observe that an `invalid search attribute type: Unspecified` error is thrown before this change.

**Potential risks**
Unclear.

**Is hotfix candidate?**
The community should be notified that this bug existed, and that they should upgrade to fix it.

### CODE REVIEW

File: service/history/archival/archiver_test.go [hunk 1]
```diff
@@ -53,33 +55,23 @@ func TestArchiver(t *testing.T) {
...
 		RateLimiterWaitErr   error
 		Targets              []Target
+		SearchAttributes     *common.SearchAttributes
+		SearchAttributesErr  error
+		NameTypeMap          searchattribute.NameTypeMap
+		NameTypeMapErr       error
 
 		ExpectArchiveHistory    bool
 		ExpectArchiveVisibility bool
-		ExpectedMetrics         []expectedMetric
```
Comment (MichaelSnowden) [inline service/history/archival/archiver_test.go:59]: I removed these and the log recorder messages because they're too much of a pain to maintain

File: service/history/archival/archiver.go [hunk 2]
```diff
@@ -212,8 +219,13 @@ func (a *archiver) archiveVisibility(ctx context.Context, request *Request, logg
 		return err
 	}
 
+	saTypeMap, err := a.searchAttributeProvider.GetSearchAttributes(a.visibilityManager.GetIndexName(), false)
+	if err != nil {
+		return err
+	}
+
 	// It is safe to pass nil to typeMap here because search attributes type must be embedded by caller.
```
Comment (dnr) [inline service/history/archival/archiver.go:227]: comment should change since we're not passing nil anymore

File: service/history/archival/archiver_test.go [hunk 3]
```diff
@@ -32,18 +32,20 @@ import (
...
 	"go.temporal.io/server/common/metrics"
+	"go.temporal.io/server/common/payload"
+	"go.temporal.io/server/common/persistence/visibility/manager"
 	"go.temporal.io/server/common/quotas"
 	"go.temporal.io/server/common/sdk"
+	"go.temporal.io/server/common/searchattribute"
 	"go.temporal.io/server/common/testing/mocksdk"
 	"go.temporal.io/server/service/history/configs"
+	"go.uber.org/fx"
+	"go.uber.org/multierr"
```
Comment (dnr) [inline service/history/archival/archiver_test.go:48]: put these imports up higher in the third party section

File: service/history/archival/archiver.go [hunk 4]
```diff
@@ -212,8 +219,13 @@ func (a *archiver) archiveVisibility(ctx context.Context, request *Request, logg
 		return err
 	}
 
+	saTypeMap, err := a.searchAttributeProvider.GetSearchAttributes(a.visibilityManager.GetIndexName(), false)
```
Comment (dnr) [inline service/history/archival/archiver.go:222]: maybe: comment about why we're calling this here? not sure if it's necessary

**Review by rodrigozhou — APPROVED** [review]
Please, address @dnr comments.
