### PR TITLE
Fix batcher

### LINKED ISSUE #2077: Batch operation doesn't work with default docker-compose
## Expected Behavior
Terminate batch operation works and terminates running workflows.

## Actual Behavior
Terminate batch operation doesn't work.

## Steps to Reproduce the Problem
```
tctl batch start --query "ExecutionStatus='Running'" --reason "Kill'Em All" --bt terminate
```

Server logs will show:

```
temporal                | {"level":"error","ts":"2021-10-20T15:45:34.271Z","msg":"Activity error.","Namespace":"temporal-system","TaskQueue":"temporal-sys-batcher-taskqueue","WorkerID":"65@7a8a1d05f1be@",
"WorkflowID":"fc3e96f3-90bf-4795-aa34-047138986c9a","RunID":"773caed4-f105-4103-861b-81728b41db27","ActivityType":"temporal-sys-batch-activity","Attempt":1,"Error":"last connection error: connection error
: desc = \"transport: Error while dialing dial tcp 127.0.0.1:7233: connect: connection refused\"","logging-call-at":"internal_task_pollers.go:863","stacktrace":"go.temporal.io/server/common/log.(*zapLogge
r).Error\n\t/temporal/common/log/zap_logger.go:143\ngo.temporal.io/server/common/log.(*SdkLogger).Error\n\t/temporal/common/log/sdk_logger.go:83\ngo.temporal.io/sdk/internal.(*activityTaskHandlerImpl).Exe
cute\n\t/go/pkg/mod/go.temporal.io/sdk@v1.9.0/internal/internal_task_handlers.go:1837\ngo.temporal.io/sdk/internal.(*activityTaskPoller).ProcessTask\n\t/go/pkg/mod/go.temporal.io/sdk@v1.9.0/internal/inter
nal_task_pollers.go:863\ngo.temporal.io/sdk/internal.(*baseWorker).processTask\n\t/go/pkg/mod/go.temporal.io/sdk@v1.9.0/internal/internal_worker_base.go:343"}
```

This happens because `127.0.0.1` is hardcoded in [config_template.yaml](https://github.com/temporalio/temporal/blob/master/docker/config_template.yaml#L283).

### PR DESCRIPTION
**Pull request by alexshtin**
**What changed?**
Batcher now uses correct SDK client to connect to the server. Previously configuration from replication config was used.

**Why?**
Closed #2077.

**How did you test it?**
Existing tests, manual run.

**Potential risks**
No risks.

**Is hotfix candidate?**
No.

### CODE REVIEW

**Review by yiminc — APPROVED** [review]

File: service/history/handler.go [hunk 1]
```diff
@@ -157,7 +158,12 @@ var (
 )
 
 // NewHandler creates a thrift handler for the history service
-func NewHandler(args NewHandlerArgs) *Handler {
+func NewHandler(args NewHandlerArgs) (*Handler, error) {
+	sdkSystemClient, err := args.SdkClientFactory.NewSystemClient(args.Logger)
```
Comment (Ardagan) [inline service/history/handler.go:162]: why not extract this into provider and inject SystemSdkClient?

Comment (alexshtin) [reply service/history/handler.go]: Fixed!

File: common/sdk/factory.go [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+func NewClientFactory(hostPort string, tlsConfig *tls.Config, scope tally.Scope) *clientFactory {
+	return &clientFactory{
+		hostPort:  hostPort,
+		tlsConfig: tlsConfig,
+		scope:     scope,
+	}
+}
+
+func (f *clientFactory) NewClient(namespaceName string, logger log.Logger) (sdkclient.Client, error) {
+	sdkClient, err := sdkclient.NewClient(sdkclient.Options{
```
Comment (Ardagan) [inline common/sdk/factory.go:64]: just return here.

**Review by Ardagan — APPROVED** [review]
