### PR TITLE
Fix flaky versioning integration test

### LINKED ISSUE #4640: Flaky test: TestDisableUserData_QueryTimesOut
## Expected Behavior
Test should always pass

## Actual Behavior
```
--- FAIL: TestVersioningIntegrationSuite (15.42s)
    --- FAIL: TestVersioningIntegrationSuite/TestDisableUserData_QueryTimesOut (0.04s)
        versioning_test.go:1631: 
                Error Trace:    /Users/ycyang/temporalio/temporal/tests/versioning_test.go:1631
                Error:          Should be in error chain:
                                expected: %!q(**serviceerror.DeadlineExceeded=0x14000c9e780)
                                in chain: 
                Test:           TestVersioningIntegrationSuite/TestDisableUserData_QueryTimesOut
```

## Steps to Reproduce the Problem

  1. Run ^ test using master branch (I was using commit `7e2de6902fa98cc98884b4f4003b5a0e8a91936e`). It fails in like 1-2 out of 10 runs.
  1.
  1.

## Specifications

  - Version:
  - Platform:

### PR DESCRIPTION
**Pull request by dnr**
**What changed?**
- Fix flaky `TestDisableUserData_QueryTimesOut` (it should actually fail with `FailedPrecondition`)
- Other small test cleanups

**Why?**
Fixes #4640

**How did you test it?**
is tests

Also tried a variation where the test workflow sleeps instead of completing. In that case the query ran on the sticky queue so it needed more sleep or to reset sticky to pass. I don't think we need to keep both variation though.

### CODE REVIEW

File: tests/versioning_test.go [hunk 1]
```diff
@@ -1591,19 +1596,28 @@ func (s *versioningIntegSuite) TestDisableUserData_WorkflowGetsStuck() {
...
 	tq := s.T().Name()
 	v1 := s.prefixed("v1")
 	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
 	defer cancel()
+
 	s.addNewDefaultBuildId(ctx, tq, v1)
 
 	var runs atomic.Int32
 	wf := func(ctx workflow.Context) error {
-		return workflow.SetQueryHandler(ctx, "query", func() (string, error) {
```
Comment (MichaelSnowden) [inline tests/versioning_test.go:1603]: Why remove this?

**Review by MichaelSnowden — APPROVED** [review]

File: tests/versioning_test.go (hunk 1 above)
Comment (dnr) [reply tests/versioning_test.go:1603]: It confused me when I was messing with the test.. I added code after that and expected it to run. I think it's clearer to separate `SetQueryHandler`  and have the workflow do an explicit return
