### PR TITLE
Fix error prone retry time implementation

### LINKED ISSUE #1675: Activity Retry Policy does not seem to be respected
## Expected Behavior

Retries should start respecting the initial delay and backoff coefficient, and then but the distance between retries is capped to the `MaximumInterval` value which is 1 hour in our case.

## Actual Behavior

All retries are 1 hour apart. 

## Steps to Reproduce the Problem

1. Make an Activity fail. Configure the Activity as so:

```
  10  ActivityTaskScheduled                            
  {ActivityId:10,
    ActivityType:{Name:waitForCompletionActivity},
    TaskQueue:{Name:api, Kind:Normal},
    Input:["e1877661-2ce8-455b-b2d6-fb0c0cdfd98d_11"],
    ScheduleToCloseTimeout:24h0m0s, ScheduleToStartTimeout:5m0s,
    StartToCloseTimeout:24h0m0s, HeartbeatTimeout:0s,
    WorkflowTaskCompletedEventId:9, RetryPolicy:{InitialInterval:200ms,
    BackoffCoefficient:2, MaximumInterval:1h0m0s, MaximumAttempts:10,
    NonRetryableErrorTypes:[]}}
 ```

2.  Run the Activity. 

3. Now try again without the `MaximimInterval` - the retries go back to normal and behave as expected

Note that I haven't run in a Sandboxed environment.

## Specifications

  - Version: `temporalio/server:1.9.2`
  - Platform: linux,amd64

More conversation: https://temporalio.slack.com/archives/CTRCR8RBP/p1624476720272300

### PR DESCRIPTION
**Pull request by wxing1292**
**What changed?**
* Do not truncate time.Duration to seconds, if conversion is necessary for math, use nano seconds
* Convert core retry function logic to use nil instead of `0 mean infinite`

Close #1675

**Why?**
Fix bug that sub second retry delay is treated as 0

**How did you test it?**
Unit tests

**Potential risks**
N/A

**Is hotfix candidate?**
Maybe

### CODE REVIEW

File: service/history/workflow/mutable_state_impl.go [hunk 1]
```diff
@@ -3515,6 +3515,8 @@ func (e *MutableStateImpl) RetryActivity(
 		return retryState, nil
 	}
 
+	fmt.Printf("#####\n%v\n#####\n", backoffInterval)
```
Comment (yiminc) [inline service/history/workflow/mutable_state_impl.go:3518]: remove

File: service/history/workflow/retry.go [hunk 2]
```diff
@@ -32,26 +32,63 @@ import (
...
 	backoffCoefficient float64,
 	failure *failurepb.Failure,
 	nonRetryableTypes []string,
 ) (time.Duration, enumspb.RetryState) {
 
-	// Sanity check to make sure currentAttemptCounterValue started with 1.
-	if currentAttemptCounterValue < 1 {
-		currentAttemptCounterValue = 1
+	var initIntervalDuration *time.Duration
+	if initInterval != nil && *initInterval > 0 {
```
Comment (yiminc) [inline service/history/workflow/retry.go:50]: should keep the sanity check for cuurentAttempt start with 1.

File: service/history/workflow/retry.go [hunk 3]
```diff
@@ -63,33 +100,25 @@ func getBackoffInterval(
 	// (we made 1 non-retry attempt already) and condition (currentAttemptCounterValue+1 > maxAttempts) will be false.
 	// With 2nd retry, currentAttemptCounterValue will be 2 (1 non-retry + 1 retry attempt already made) and
 	// condition (currentAttemptCounterValue+1 > maxAttempts) will be true (means stop retrying, we tried 2 times already).
-	if maxAttempts > 0 && currentAttemptCounterValue+1 > maxAttempts {
+	if maxAttempts > 0 && currentAttempt+1 > maxAttempts {
```
Comment (alexshtin) [inline service/history/workflow/retry.go:103]: Please rename `currentAttemptCounterValue` in the comment above also.

File: service/history/workflow/retry.go [hunk 4]
```diff
@@ -63,33 +100,25 @@ func getBackoffInterval(
...
-			nextIntervalSeconds = maxIntervalSeconds
-		} else {
-			return backoff.NoBackoff, enumspb.RETRY_STATE_TIMEOUT
-		}
-	}
-
-	if maxIntervalSeconds > 0 && nextIntervalSeconds > maxIntervalSeconds {
-		// cap next interval to MaxInterval
-		nextIntervalSeconds = maxIntervalSeconds
+	interval := time.Duration(int64(float64(initInterval.Nanoseconds()) * math.Pow(backoffCoefficient, float64(currentAttempt-1))))
```
Comment (alexshtin) [inline service/history/workflow/retry.go:107]: `initInterval` can be `nil` here and it will panic. Worth to add test and pass `nil` to all pointer parameters.

File: service/history/workflow/retry.go (hunk 3 above)
Comment (alexshtin) [reply service/history/workflow/retry.go:103]: I think this is better:
```suggestion
	if maxAttempts > 0 && currentAttempt >= maxAttempts {
```

File: service/history/workflow/retry.go [hunk 5]
```diff
@@ -32,26 +32,63 @@ import (
...
+		backoffCoefficient,
+		failure,
+		nonRetryableTypes,
+	)
+}
+
+// TODO treat 0 as 0, not infinite
+// TODO use getBackoffIntervalWrapper for retry calculation, deprecate the 0 -> nil conversion
+
+func getBackoffIntervalWrapper(
```
Comment (alexshtin) [inline service/history/workflow/retry.go:80]: This is not a wrapper. This is wrappable. I think `getBackoffIntervalInternal` or `getBackoffIntervalNilable` are better names here.

**Review by alexshtin — APPROVED** [review]

File: service/history/workflow/retry.go [hunk 6]
```diff
@@ -35,22 +35,37 @@ import (
...
-	// Sanity check to make sure currentAttemptCounterValue started with 1.
-	if currentAttemptCounterValue < 1 {
-		currentAttemptCounterValue = 1
+	// TODO remove below checks, most are already set with correct values
+	if currentAttempt < 1 {
+		currentAttempt = 1
+	}
+
+	if initInterval == nil {
+		initInterval = timestamp.DurationPtr(time.Duration(0))
```
Comment (yiminc) [inline service/history/workflow/retry.go:58]: initial interval set to 0 would cause trouble because backoff is based on initial interval. I believe the default we set is 1s

File: service/history/workflow/mutable_state_impl.go (hunk 1 above)
Comment (yiminc) [reply service/history/workflow/mutable_state_impl.go]: please remove.

File: service/history/workflow/retry.go (hunk 6 above)
Comment (wxing1292) [reply service/history/workflow/retry.go:58]: there is already a default set when creating the activity at the beginning.
https://github.com/temporalio/temporal/blob/v1.10.4/service/history/commandChecker.go#L671
https://github.com/temporalio/temporal/blob/v1.10.4/common/util.go#L485
https://github.com/temporalio/temporal/blob/v1.10.4/common/util.go#L89

Comment (yiminc) [reply service/history/workflow/retry.go:58]: Yes, that is my point. The default is 1s. The nil case should not happen, so we either throw when we see the nil, or we set it to default of 1s. Set to 0 will cause other trouble and hide the issue. For example, based on the logic below, 0 interval might cause no retry.

Comment (wxing1292) [reply service/history/workflow/retry.go:58]: overhaul of code is required to making things right
* `0 is 0, nil is nil is required`
* rely on input validation to correctly set attributes and later use the variables without overriding (sanity check & panic should be allowed)

this PR is going to be cherry picked for a patch release, so prefer minimal changes.

Comment (alexshtin) [reply service/history/workflow/retry.go:58]: So both `0` and `nil` are not valid here. I would suggest:
```suggestion
       if initInterval == nil || *initialInterval == 0 {
		return backoff.NoBackoff, enumspb.RETRY_STATE_RETRY_POLICY_NOT_SET
```

**Review by yiminc — APPROVED** [review]

File: service/history/workflow/retry.go (hunk 6 above)
Comment (wxing1292) [reply service/history/workflow/retry.go:58]: the code below will either override init interval to max interval (if not nil) or just return no retry

**Review by alexshtin — APPROVED** [review]
