### PR TITLE
Remove frontend handler retries

### LINKED ISSUE #3282: Frontend handler retries may lead to InvalidArgument errors when starting new workflow
## Expected Behavior
New workflow starts w/o errors.

## Actual Behavior
New workflow fails to start, and `InvalidArgument` error with message indicating that search attribute is not found returned.

### PR DESCRIPTION
**Pull request by alexshtin**
**What changed?**
Remove frontend handler retries.

**Why?** 
Retries on frontend handler level may lead to unexpected `InvalidArgument` errors. Closes #3282.

**How did you test it?**
Existing tests.

**Potential risks**
No risks.

**Is hotfix candidate?**
Yes.

### CODE REVIEW

**Review by yycptt — APPROVED** [review]
Maybe only land to 1.17 release branch for now? And pick to master after our discussion about the long term solution tomorrow?

**Comment by alexshtin** [comment]
We decided not to do this. All commits should go on `master` branch first and then get cherry picked to release branches to simplify downstream merges.

File: common/util.go [hunk 1]
```diff
@@ -63,10 +63,10 @@ const (
 	frontendClientRetryMaxAttempts     = 2
 
 	historyClientRetryInitialInterval = 50 * time.Millisecond
-	historyClientRetryMaxAttempts     = 2
+	historyClientRetryMaxAttempts     = 5
 
 	matchingClientRetryInitialInterval = 1000 * time.Millisecond
-	matchingClientRetryMaxAttempts     = 2
+	matchingClientRetryMaxAttempts     = 5
```
Comment (yiminc) [inline common/util.go:69]: Why doing this change?

**Review by yiminc — CHANGES_REQUESTED** [review]

File: common/util.go (hunk 1 above)
Comment (alexshtin) [reply common/util.go:69]: Because we don't retry on handler level anymore, it makes sense to increase number of attempts from client themselves. `2` is too small for overall retry attempts.

**Review by yiminc — APPROVED** [review]
